### ISSUE TITLE
Отсутсвует строгая гарантия безопасности

### ISSUE THREAD

**Issue by simplydesigner** [Balanar300hp/stack_tests#2]
Отсутсвует строгая гарантия безопасности в методе push

https://github.com/Balanar300hp/stack_tests/blob/2a4f42bddca53e2c0e812743234229f95a315ca0/include/stack.h#L11

**Comment by kayrosik** [comment]
https://github.com/Balanar300hp/stack_tests/commit/c66567034579837d3b1be62d9ce970be9f453c3e
